// Code generated by goctl. DO NOT EDIT.
package types

type CountWithTagReq struct {
	Tag string `path:"tag"`
}

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
