// Code generated by goctl. DO NOT EDIT.
package types

type CountReq struct {
}

type CountWithTagReq struct {
	Tag string `json:"tags",path:"tag"`
}

type CountReply struct {
	Count int64 `json:"count"`
}
