// Code generated by goctl. DO NOT EDIT.
package types

type CountWithTagReq struct {
	Tag string `json:"tag",path:"tag"`
}

type CountReply struct {
	Count int64 `json:"count"`
}

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
