# 拉取 Go 语言最新的基础镜像
FROM golang:1.17 as Builder


# 设置 GOPROXY 环境变量
ENV GOPROXY="https://goproxy.cn"
# 开启go.mod
ENV GO111MODULE on

# 在容器内设置 /app 为当前工作目录
WORKDIR /app

# 把文件复制到当前工作目录
COPY . .

# 下载全部依赖项
RUN go mod download

# 编译项目
RUN GOOS=linux CGO_ENABLED=0 go build -o admin_api service/admin/api/admin.go

FROM alpine:3.7
RUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.7/main/ > /etc/apk/repositories

# 设置时区
RUN apk update && apk add tzdata

# 暴露 9999 端口
EXPOSE 9999

WORKDIR /app

COPY --from=Builder /app/admin_api .
COPY --from=Builder /app/service/admin/api/etc/admin-api.yaml ./etc/

# 执行可执行文件
CMD ["./admin_api", "-f", "./etc/admin-api.yaml"]