// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	blogRpc "qianxi-blog/service/admin/api/internal/handler/blogRpc"
	userApi "qianxi-blog/service/admin/api/internal/handler/userApi"
	"qianxi-blog/service/admin/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/user/login",
				Handler: userApi.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/post/update",
				Handler: blogRpc.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/post/id/:id/page/:page/size/:size",
				Handler: blogRpc.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/post/update/content",
				Handler: blogRpc.UpdatWithContentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/post/insert",
				Handler: blogRpc.InsertPostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/comment/id/:id/postid/:postid",
				Handler: blogRpc.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/system/update",
				Handler: blogRpc.UpdateSystemInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/system",
				Handler: blogRpc.AllSystemInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/countinfo",
				Handler: blogRpc.CountInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/post/page/:page/size/:size",
				Handler: blogRpc.PostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/post/count",
				Handler: blogRpc.PostCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/comment/count",
				Handler: blogRpc.CommentCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/post/id/:id",
				Handler: blogRpc.PostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/comment/page/:page/size/:size",
				Handler: blogRpc.CommentsHandler(serverCtx),
			},
		},
	)
}
