// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	commentApi "qianxi-blog/service/blog/api/internal/handler/commentApi"
	postApi "qianxi-blog/service/blog/api/internal/handler/postApi"
	"qianxi-blog/service/blog/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post/count",
				Handler: postApi.CountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/count/tag/:tag",
				Handler: postApi.CountWithTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/page/:page/size/:size",
				Handler: postApi.PostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/page/:page/size/:size/tag/:tag",
				Handler: postApi.PostsWithTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/id/:id",
				Handler: postApi.PostHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/save",
				Handler: commentApi.SaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comment/id/:id/login/:login",
				Handler: commentApi.DeleteHandler(serverCtx),
			},
		},
	)
}
